services:
  otel-collector:
    image: otel/opentelemetry-collector
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
    depends_on:
      - jaeger-all-in-one
      - zipkin
      - prometheus
  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      # - "6831:6831/udp" # UDP port for Jaeger agent
      - "16686:16686" # Web UI
      - "14250:14250" # Accept model.proto directly (Legacy)
      - "14317:14317" # OTLP gRPC receiver
      - "14318:14318" # OTLP http receiver
      # - "14268:14268" # Accept jaeger.thrift directly
      # - "14269:14269" 
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
      COLLECTOR_OTLP_GRPC_HOST_PORT: 0.0.0.0:14317
      COLLECTOR_OTLP_HTTP_HOST_PORT: 0.0.0.0:14318
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"

# rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 192.168.107.4:14317: connect: connection refused\
# rpc error: 
#   code = Unavailable 
#   desc = connection error: 
#     desc = "transport: Error while dialing: dial tcp 192.168.107.4:14317: connect: connection refused"